##' convert a plot to grob object
##'
##'
##' @title as.grob
##' @param plot base or grid plot, or graphic object generated by ggplot, lattice, etc.
##' @return grob object
##' @export
##' @importFrom base2grob base2grob
##' @importFrom ggplot2 ggplotGrob
##' @importFrom rvcheck get_fun_from_pkg
##' @author guangchuang yu
as.grob <- function(plot) {
    ## plot_expr <- quo_name(enexpr(plot))
    if (inherits(plot, "expression") ||
        inherits(plot, "formula") ||
        inherits(plot, "function")) {

        p <- tryCatch(base2grob(plot),
                      error = function(e) NULL)

        if (is.null(p)) {
            p <- grid::grid.grabExpr(base_plot_fun(plot)(), warn=0)
        }

        return(p)
    }

    if (inherits(plot, "ggplot")) {
        p <- ggplotGrob(plot)
    } else if (inherits(plot, "meme")) {
        memeGrob <- get_fun_from_pkg("meme", "memeGrob")
        p <- memeGrob(plot)
    } else if (inherits(plot, "trellis") ||
               inherits(plot, "upset")) {
        p <- grid::grid.grabExpr(print(plot))
    } else if (inherits(plot, "grob")) {
        p <- plot
    } else {
        message("fail to convert ...")
        return(NULL)
        ## p <- grid::grid.grabExpr(parse(text = plot_expr), warn=0)
    }

    return(p)
}

base_plot_fun <- getFromNamespace("base_plot_fun", "base2grob")
